# Generated by Django 3.0.8 on 2021-01-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saved_News',
            new_name='SavedNews',
        ),
    ]
