# Generated by Django 3.0.8 on 2021-01-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_auto_20210121_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savednews',
            name='published_date',
            field=models.CharField(max_length=400),
        ),
    ]
