# Generated by Django 3.0.8 on 2021-01-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_auto_20210121_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savednews',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
